name: Deploy

on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.svg'
      - '**.gif'
      - '**.png'
      - '.idea/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3

      - name: Build server
        run: mvn clean package deploy