name: Deploy

on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.svg'
      - '**.gif'
      - '**.png'
      - '.idea/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3

      - name: Deploy
        run: JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/ && mvn clean package deploy
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}